defaults: &defaults
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: db
  username: postgres
  password:

development:
  <<: *defaults
  database: app_development

test:
  <<: *defaults
  database: app_test

production:
  <<: *defaults
  database: app_production
